# Add labels based on file paths - v6 format
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '*.md'
      - 'docs/**'
      - '*.rst'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'test/**'
      - 'tests/**'
      - '**/test_*.py'
      - '**/*_test.py'

ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/*.yml'
      - '.github/*.yaml'
      - '.pre-commit-config.yaml'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'uv.lock'

velodyne:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/hilspy/velodyne/**'

core:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/hilspy/*.py'
      - 'src/hilspy/__init__.py'

python:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.py'

github-actions:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
